version: '3.7'
services:
  bot:
    container_name: telegram-publisher
    build: 
      context: .
      dockerfile: dockerfile
    networks:
      - main-net
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      KAFKA_URL: ${KAFKA_URL}
networks:
  main-net:
    external: true